services:
  - type: web
    name: sphelele
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true

  - type: web
    name: sphelele-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn beauty_booking.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: beauty_booking.settings
