const state = { service: 'HD Lace Installation', price: 500, deposit: 150, duration: 150, date: '25 September', dateLabel: 'Friday, 25 September 2026', time: '09:00', timezone: 'Africa/Johannesburg (SAST)', paidBooking: null };
const availability = { '25 September': ['11:00'], '26 September': ['10:00', '15:00'], '28 September': ['12:00'], '29 September': [] };
const services = { 'HD Lace Installation': 150, 'Frontal Installation': 120, 'Classic Lashes': 90, 'Hybrid Lashes': 105 };
const $ = selector => document.querySelector(selector);
const $$ = selector => document.querySelectorAll(selector);
function formatDuration(minutes) { return `${Math.floor(minutes / 60)} hr${minutes >= 120 ? 's' : ''}${minutes % 60 ? ` ${minutes % 60} min` : ''}`; }
function setStep(step) { $$('.booking-step').forEach(item => item.classList.remove('active-step')); $(`#step${step === 1 ? 'One' : step === 2 ? 'Two' : 'Three'}`).classList.add('active-step'); $$('.step-indicator span').forEach((item, index) => item.classList.toggle('active', index < step)); if (step === 2) renderSlots(); }
function updateSummary() { $('#summaryService').textContent = state.service; $('#summaryTotal').textContent = `R${state.price}`; $('#summaryDeposit').textContent = `R${state.deposit}`; $('#summaryTime').textContent = state.time; }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
function formatWhatsAppNumber(phone) { const digits = phone.replace(/\D/g, ''); if (digits.startsWith('0')) return `27${digits.slice(1)}`; if (digits.startsWith('27')) return digits; return digits; }
function timeToMinutes(time) { const [hours, minutes] = time.split(':').map(Number); return hours * 60 + minutes; }
function minutesToTime(minutes) { return `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`; }
function renderSlots() { const slots = $('#timeSlots'); const blocked = availability[state.date] || []; const opening = 8 * 60; const closing = 19 * 60; const step = 60; const lunchStart = 13 * 60; if (!document.querySelector('.hours-note')) { const note = document.createElement('div'); note.className = 'hours-note'; note.innerHTML = 'Open every day · <strong>08:00–19:00</strong>'; slots.parentElement.insertBefore(note, document.querySelector('.timezone-note')); } slots.innerHTML = ''; $('#selectedDateLabel').textContent = `${state.dateLabel} · ${formatDuration(state.duration)}`; $('#slotHint').textContent = `${formatDuration(state.duration)} appointment`; for (let start = opening; start + state.duration <= closing; start += step) { const time = minutesToTime(start); const overlapsLunch = start < lunchStart + 60 && start + state.duration > lunchStart; const isBooked = blocked.includes(time); const button = document.createElement('button'); button.className = `time${isBooked ? ' booked' : ''}${overlapsLunch ? ' lunch' : ''}${time === state.time && !isBooked && !overlapsLunch ? ' selected' : ''}`; button.disabled = isBooked || overlapsLunch; button.innerHTML = `${time}${isBooked ? '<small>Booked</small>' : overlapsLunch ? '<small>Lunch</small>' : ''}`; if (!button.disabled) button.addEventListener('click', () => { $$('.time').forEach(item => item.classList.remove('selected')); button.classList.add('selected'); state.time = time; updateSummary(); }); slots.appendChild(button); } if (!slots.querySelector('.time:not(:disabled)')) slots.innerHTML = '<p class="no-slots">No times fit this service on this date. Please choose another date.</p>'; }
function renderAdmin() { const list = $('#appointmentList'); const count = state.paidBooking ? 1 : 0; $('#bookingCount').textContent = count; $('#todayCount').textContent = count; list.innerHTML = state.paidBooking ? `<article class="appointment"><time>${state.paidBooking.time}<small>Confirmed</small></time><div class="appointment-person"><div class="avatar coral">${state.paidBooking.initials}</div><div><h4>${state.paidBooking.name}</h4><p>${state.paidBooking.service} · ${state.paidBooking.date}</p><span class="wa">${state.paidBooking.note || 'No note added'}</span></div></div><span class="paid">● Deposit paid</span></article>` : '<div class="empty-admin">No paid bookings yet.</div>'; }
$$('.choice').forEach(choice => choice.addEventListener('click', () => { $$('.choice').forEach(item => item.classList.remove('selected')); choice.classList.add('selected'); state.service = choice.dataset.service; state.price = Number(choice.dataset.price); state.deposit = Number(choice.dataset.deposit); state.duration = services[state.service]; updateSummary(); }));
$$('.date').forEach(date => date.addEventListener('click', () => { $$('.date').forEach(item => item.classList.remove('selected')); date.classList.add('selected'); state.date = date.dataset.date; state.dateLabel = date.dataset.label; state.time = '09:00'; renderSlots(); }));
$$('.next-step').forEach(button => button.addEventListener('click', () => setStep(Number(button.dataset.next))));
$$('.back-step').forEach(button => button.addEventListener('click', () => setStep(Number(button.dataset.back))));
$('#timezoneSelect').addEventListener('change', event => { state.timezone = event.target.value; $('.timezone-note strong').textContent = state.timezone; showToast(`Times shown in ${state.timezone}.`); });
$('#payButton').addEventListener('click', () => { const name = $('#clientName').value.trim(); const phone = $('#clientPhone').value.trim(); if (!name || !phone) { showToast('Add your name and WhatsApp number first.'); return; } state.paidBooking = { name, phone, service: state.service, date: `${state.dateLabel} at ${state.time}`, time: state.time, timezone: state.timezone, note: $('#clientNote').value.trim(), initials: name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase() }; renderAdmin(); $('#confirmedName').textContent = name.split(' ')[0]; $('#confirmationDetails').textContent = `${state.service} is confirmed for ${state.dateLabel} at ${state.time} (${state.timezone}). Confirmation and reminders will be sent to your WhatsApp number.`; $('#whatsappConfirm').href = `https://wa.me/${formatWhatsAppNumber(phone)}?text=${encodeURIComponent(`Hi ${name}, your ${state.service} appointment is confirmed for ${state.dateLabel} at ${state.time} (${state.timezone}).`)}`; $$('.booking-step').forEach(item => item.style.display = 'none'); $('#confirmation').classList.add('show'); showToast('Payment confirmed.'); });
$('#rescheduleButton').addEventListener('click', () => { $('#confirmation').classList.remove('show'); $$('.booking-step').forEach(item => item.style.display = ''); setStep(2); showToast('Choose a new date and time.'); });
$('#cancelButton').addEventListener('click', () => { state.paidBooking = null; renderAdmin(); $('#confirmationDetails').textContent = 'This booking has been cancelled. Any deposit refund is handled according to the studio policy.'; $('#confirmation').classList.add('cancelled'); $('#cancelButton').disabled = true; $('#rescheduleButton').disabled = true; showToast('Booking cancelled.'); });
$('#ownerToggle').addEventListener('click', () => { $('#dashboard').classList.add('show'); $('#dashboard').setAttribute('aria-hidden', 'false'); document.body.classList.add('dashboard-open'); });
$('.close-dashboard').addEventListener('click', () => { $('#dashboard').classList.remove('show'); $('#dashboard').setAttribute('aria-hidden', 'true'); document.body.classList.remove('dashboard-open'); });
$('#blockTime').addEventListener('click', () => $('#blockModal').classList.add('show')); $('.close-modal').addEventListener('click', () => $('#blockModal').classList.remove('show')); $('#saveBlock').addEventListener('click', () => { $('#blockModal').classList.remove('show'); showToast('Time blocked.'); }); $('#blockModal').addEventListener('click', event => { if (event.target.id === 'blockModal') $('#blockModal').classList.remove('show'); });
updateSummary(); renderSlots(); renderAdmin();
